name: Build and Test

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Change directory to app
      run: cd app

    - name: Build with Maven
      run: mvn -B package

    - name: Run tests
      run: mvn --batch-mode --update-snapshots verify